name: Test build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Add explicit permissions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: npm run build
        env:
          MARKKET_URL: ${{ secrets.MARKKET_URL }}
          MARKKET_STORE_SLUG: next
          BUILD_MODE: static
          NEXT_PUBLIC_MARKKET_API: https://api.markket.place
          NEXT_PUBLIC_MARKKET_STORE_SLUG: next
          NEXT_PUBLIC_MARKKETPLACE_URL: https://markket.place

